### ISSUE TITLE
Dragonflight. БФА. Квесты на автокомплит. Боларус. Альянс.

### ISSUE THREAD

**Issue by m1LOMAN** [admadm123/Turbo---dragonwow#106]
Выпишу неработающие задания на которые надо потратить время над их механиками. Предлагаю автокомлитить.
1) Лучший номер. https://www.wowhead.com/ru/quest=53331/лучший-номер
2) Охота на горностаев https://www.wowhead.com/ru/quest=48077/охота-на-горностаев
3) Разумеется, идеальная лошадь https://www.wowhead.com/ru/quest=48903/разумеется-идеальная-лошадь
4) Стой спокойно https://www.wowhead.com/ru/quest=49394/стой-спокойно
5) Укрощение по-сорвиголовски https://www.wowhead.com/ru/quest=49417/укрощение-по-сорвиголовски
6) Шахтерская операция https://www.wowhead.com/ru/quest=50351/шахтерская-операция
7) Красота маркетинга https://www.wowhead.com/ru/quest=49531/красота-маркетинга

**Comment by admadm123** [comment]
![image](https://github.com/admadm123/Turbo---dragonwow/assets/63059326/61ae8380-8020-443c-8d00-3526f7dac78e)
половину квестов которые ты выписал работают нормально

**Comment by admadm123** [comment]
Локальными заданиями я не занимаюсь quest=53331

**Comment by admadm123** [comment]
quest=48903/разумеется-идеальная-лошадь 
автокомплит

**Comment by m1LOMAN** [comment]
8) История с привидениями https://www.wowhead.com/ru/quest=48475/история-с-привидениями

**Comment by m1LOMAN** [comment]
А как понять локальные задания? Просто в этом не шарю.

**Comment by admadm123** [comment]
ALL FIX

**Comment by m1LOMAN** [comment]
10) Устройство для осмотра https://www.wowhead.com/ru/quest=51426/устройство-для-осмотра
11) Не будьте свиньями https://www.wowhead.com/ru/quest=47950/не-будьте-свиньями QuestID - 47950
12) Спасти их шкуры https://www.wowhead.com/ru/quest=47946/спасти-их-шкуры QuestID - 47946
13) Пора заканчивать этот фарш https://www.wowhead.com/ru/quest=47948/пора-заканчивать-этот-фарш - Нет НПС которого нужно убить QuestID - 47948
14) Лига искателей приключений https://www.wowhead.com/ru/quest=48793/лига-искателей-приключений QuestID - 48793
15) Ошибки случаются https://www.wowhead.com/ru/quest=48804/ошибки-случаются QuestID - 48804
16) Финальная стадия https://www.wowhead.com/ru/quest=48853/финальная-стадия - Можно сделать конец квеста после убийства моба QuestID - 48853

**Comment by admadm123** [comment]
FIX
