### ISSUE TITLE
Dragonflight. Классика. НПС. Волк племени Иглогривых. Северные степи. Орда.

### ISSUE THREAD

**Issue by m1LOMAN** [admadm123/Turbo---dragonwow#65]
Неважно кто выйдет против меня, тот упадёт с трех ударов. Ауф. 
Волчара слишком долбанутый.
![image](https://github.com/admadm123/dragonwow/assets/148571583/32a75683-e9b0-433b-aad6-dc2aeca7ee71)

**Comment by admadm123** [comment]
сейчас посмотрим
