### ISSUE TITLE
Dragonflight. Классика. Не сменилась фаза территорий перед Подгородом.

### ISSUE THREAD

**Issue by m1LOMAN** [admadm123/Turbo---dragonwow#76]
Не поменялась фаза в территории перед Подгородом. Сейчас она в фазе БФА.
![image](https://github.com/admadm123/dragonwow/assets/148571583/68369990-323c-479a-bed4-ecba1124e173)

**Comment by m1LOMAN** [comment]
![image](https://github.com/admadm123/dragonwow/assets/148571583/db8a86c0-9c7a-46f9-ac9f-ff50dedf5a10)

**Comment by m1LOMAN** [comment]
Есть просто проблема в том что из Луносвета и Подгорода, никак не попасть в Оргриммар или в Нордскол. Ты просто застреваешь на Восточных землях и всё. (если ты не маг, они то порталы поставить могут, хотя надо проверить)

**Comment by admadm123** [comment]
fix
