### ISSUE TITLE
Dragonflight. Разбойник. Незаметность.

### ISSUE THREAD

**Issue by m1LOMAN** [admadm123/Turbo---dragonwow#78]
При использовании Незаметности (инвиз роги) выдаётся сразу 3 бафа невидимости разных классов. Невидимость - Мага. Камуфляж - Охотника вроде. И наша Незаметность (При этом насколько я помню в баффе Незаметность можно находиться либо очень долго, либо бесконечно)
![image](https://github.com/admadm123/dragonwow/assets/148571583/07b45dbc-0006-4898-b186-a5f4e98d9a05)

**Comment by admadm123** [comment]
fix
