### ISSUE TITLE
Dragonflight. Классика. Квест "Не лучше зомби". Тирисфальские леса. Орда.

### ISSUE THREAD

**Issue by m1LOMAN** [admadm123/Turbo---dragonwow#79]
Невозможно сдать квест. После релога нпс появляется и исчезает после того как к нему подходишь.
![image](https://github.com/admadm123/dragonwow/assets/148571583/df42a197-48e1-4e68-8a1a-3faab98d5ce9)

**Comment by admadm123** [comment]
fix
